include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    unused_element: ignore
    unused_element_parameter: ignore
    unused_local_variable: ignore
    use_build_context_synchronously: ignore
